// utils/emotionData.js
export default [
  // 情緒
  { keyword: "開心", tags: ["happy", "energetic", "pop"] },
  { keyword: "快樂", tags: ["happy", "energetic", "pop"] },
  { keyword: "高興", tags: ["happy", "energetic", "pop"] },
  { keyword: "喜悅", tags: ["happy", "joyful", "upbeat"] },
  { keyword: "愉快", tags: ["happy", "joyful", "upbeat"] },
  { keyword: "歡樂", tags: ["happy", "joyful", "upbeat"] },
  { keyword: "開懷", tags: ["happy", "joyful", "upbeat"] },

  { keyword: "難過", tags: ["sad", "slow", "piano"] },
  { keyword: "悲傷", tags: ["sad", "slow", "piano"] },
  { keyword: "傷心", tags: ["sad", "slow", "piano"] },
  { keyword: "失落", tags: ["sad", "slow", "piano"] },
  { keyword: "沮喪", tags: ["sad", "slow", "piano"] },
  { keyword: "憂傷", tags: ["sad", "slow", "piano"] },
  { keyword: "痛苦", tags: ["sad", "slow", "piano"] },
  { keyword: "淚水", tags: ["sad", "slow", "piano"] },

  { keyword: "放鬆", tags: ["chill", "lofi", "acoustic"] },
  { keyword: "輕鬆", tags: ["chill", "lofi", "acoustic"] },
  { keyword: "舒適", tags: ["chill", "lofi", "acoustic"] },
  { keyword: "悠閒", tags: ["chill", "lofi", "acoustic"] },
  { keyword: "靜謐", tags: ["chill", "lofi", "acoustic"] },
  { keyword: "輕柔", tags: ["chill", "lofi", "acoustic"] },
  { keyword: "愜意", tags: ["chill", "lofi", "acoustic"] },

  { keyword: "生氣", tags: ["angry", "rock", "metal"] },
  { keyword: "火大", tags: ["angry", "rock", "metal"] },
  { keyword: "憤慨", tags: ["angry", "rock", "metal"] },
  { keyword: "憤怒", tags: ["angry", "rock", "metal"] },
  { keyword: "暴躁", tags: ["angry", "rock", "metal"] },
  { keyword: "激烈", tags: ["angry", "rock", "metal"] },
  { keyword: "咆哮", tags: ["angry", "rock", "metal"] },

  { keyword: "戀愛", tags: ["romantic", "love", "r&b"] },
  { keyword: "曖昧", tags: ["romantic", "love", "r&b"] },
  { keyword: "甜蜜", tags: ["romantic", "love", "r&b"] },
  { keyword: "情侶", tags: ["romantic", "love", "r&b"] },
  { keyword: "愛情", tags: ["romantic", "love", "r&b"] },
  { keyword: "喜歡", tags: ["romantic", "love", "r&b"] },
  { keyword: "愛慕", tags: ["romantic", "love", "r&b"] },
  { keyword: "戀情", tags: ["romantic", "love", "r&b"] },
  { keyword: "愛戀", tags: ["romantic", "love", "r&b"] },
  { keyword: "情感", tags: ["romantic", "love", "r&b"] },
  { keyword: "愛意", tags: ["romantic", "love", "r&b"] },
  { keyword: "戀曲", tags: ["romantic", "love", "r&b"] },

  { keyword: "失戀", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "分手", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "心碎", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "痛苦", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "難忘", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "回憶", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "思念", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "遺憾", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "孤獨", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "懷念", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "痛心", tags: ["heartbreak", "sad", "ballad"] },

  { keyword: "猶豫", tags: ["hesitant", "uncertain", "soft"] },
  { keyword: "掙扎", tags: ["hesitant", "uncertain", "soft"] },
  { keyword: "徬徨", tags: ["hesitant", "uncertain", "soft"] },
  { keyword: "迷茫", tags: ["hesitant", "uncertain", "soft"] },
  { keyword: "疑惑", tags: ["hesitant", "uncertain", "soft"] },
  { keyword: "不確定", tags: ["hesitant", "uncertain", "soft"] },
  { keyword: "憂慮", tags: ["hesitant", "uncertain", "soft"] },

  { keyword: "憂鬱", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "陰鬱", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "絕望", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "失落", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "悲觀", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "黯淡", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "陰暗", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "憂傷", tags: ["melancholy", "depressed", "emo"] },

  { keyword: "興奮", tags: ["excited", "dance", "upbeat"] },
  { keyword: "嗨", tags: ["excited", "dance", "upbeat"] },
  { keyword: "激動", tags: ["excited", "dance", "upbeat"] },
  { keyword: "熱情", tags: ["excited", "dance", "upbeat"] },
  { keyword: "活力", tags: ["excited", "dance", "upbeat"] },
  { keyword: "狂歡", tags: ["excited", "dance", "upbeat"] },
  { keyword: "派對", tags: ["excited", "dance", "upbeat"] },
  { keyword: "節奏感", tags: ["excited", "dance", "upbeat"] },

  { keyword: "緊張", tags: ["tense", "intense", "dramatic"] },
  { keyword: "壓力", tags: ["tense", "intense", "dramatic"] },
  { keyword: "緊繃", tags: ["tense", "intense", "dramatic"] },
  { keyword: "激烈", tags: ["tense", "intense", "dramatic"] },
  { keyword: "劇烈", tags: ["tense", "intense", "dramatic"] },
  { keyword: "緊湊", tags: ["tense", "intense", "dramatic"] },

  { keyword: "驚訝", tags: ["surprised", "unexpected", "quirky"] },
  { keyword: "意外", tags: ["surprised", "unexpected", "quirky"] },
  { keyword: "新奇", tags: ["surprised", "unexpected", "quirky"] },
  { keyword: "奇妙", tags: ["surprised", "unexpected", "quirky"] },

  { keyword: "疲憊", tags: ["tired", "calm", "ambient"] },
  { keyword: "累", tags: ["tired", "calm", "ambient"] },
  { keyword: "疲倦", tags: ["tired", "calm", "ambient"] },
  { keyword: "困倦", tags: ["tired", "calm", "ambient"] },
  { keyword: "無力", tags: ["tired", "calm", "ambient"] },
  { keyword: "放空", tags: ["tired", "calm", "ambient"] },

  { keyword: "焦慮", tags: ["anxious", "nervous", "chill"] },
  { keyword: "不安", tags: ["anxious", "nervous", "chill"] },

  { keyword: "無聊", tags: ["bored", "chill", "easy-listening"] },
  { keyword: "悶", tags: ["bored", "chill", "easy-listening"] },
  { keyword: "空虛", tags: ["bored", "chill", "easy-listening"] },
  { keyword: "乏味", tags: ["bored", "chill", "easy-listening"] },

  { keyword: "平靜", tags: ["calm", "relaxing", "meditative"] },
  { keyword: "安靜", tags: ["calm", "relaxing", "meditative"] },
  { keyword: "寧靜", tags: ["calm", "relaxing", "meditative"] },
  { keyword: "冥想", tags: ["calm", "relaxing", "meditative"] },
  { keyword: "靜謐", tags: ["calm", "relaxing", "meditative"] },
  { keyword: "穩定", tags: ["calm", "relaxing", "meditative"] },

  { keyword: "驚恐", tags: ["scared", "horror", "dark"] },
  { keyword: "害怕", tags: ["scared", "horror", "dark"] },
  { keyword: "恐懼", tags: ["scared", "horror", "dark"] },
  { keyword: "恐怖", tags: ["scared", "horror", "dark"] },
  { keyword: "驚悚", tags: ["scared", "horror", "dark"] },
  { keyword: "陰森", tags: ["scared", "horror", "dark"] },
  { keyword: "詭異", tags: ["scared", "horror", "dark"] },

  { keyword: "期待", tags: ["excited", "anticipation", "upbeat"] },
  { keyword: "盼望", tags: ["excited", "anticipation", "upbeat"] },
  { keyword: "渴望", tags: ["excited", "anticipation", "upbeat"] },
  { keyword: "希望", tags: ["excited", "anticipation", "upbeat"] },
  { keyword: "憧憬", tags: ["excited", "anticipation", "upbeat"] },
  { keyword: "熱切", tags: ["excited", "anticipation", "upbeat"] },
  { keyword: "興致勃勃", tags: ["excited", "anticipation", "upbeat"] },

  { keyword: "驚艷", tags: ["amazed", "wow", "inspiring"] },
  { keyword: "震撼", tags: ["amazed", "wow", "inspiring"] },
  { keyword: "讚嘆", tags: ["amazed", "wow", "inspiring"] },
  { keyword: "驚奇", tags: ["amazed", "wow", "inspiring"] },
  { keyword: "驚喜", tags: ["amazed", "wow", "inspiring"] },

  { keyword: "疑惑", tags: ["confused", "mysterious", "experimental"] },
  { keyword: "迷惑", tags: ["confused", "mysterious", "experimental"] },
  { keyword: "困惑", tags: ["confused", "mysterious", "experimental"] },
  { keyword: "不解", tags: ["confused", "mysterious", "experimental"] },
  { keyword: "迷失", tags: ["confused", "mysterious", "experimental"] },
  { keyword: "糾結", tags: ["confused", "mysterious", "experimental"] },

  { keyword: "平淡", tags: ["neutral", "background", "easy-listening"] },
  { keyword: "無味", tags: ["neutral", "background", "easy-listening"] },
  { keyword: "普通", tags: ["neutral", "background", "easy-listening"] },
  { keyword: "隨意", tags: ["neutral", "background", "easy-listening"] },
  { keyword: "平凡", tags: ["neutral", "background", "easy-listening"] },

  { keyword: "療癒", tags: ["healing", "soothing", "calming"] },
  { keyword: "舒緩", tags: ["healing", "soothing", "calming"] },
  { keyword: "安撫", tags: ["healing", "soothing", "calming"] },
  { keyword: "放鬆心情", tags: ["healing", "soothing", "calming"] },
  { keyword: "心靈", tags: ["healing", "soothing", "calming"] },
  { keyword: "靈魂", tags: ["healing", "soothing", "calming"] },
  { keyword: "舒心", tags: ["healing", "soothing", "calming"] },

  { keyword: "想睡", tags: ["sleepy", "calm", "lullaby"] },
  { keyword: "想睡覺", tags: ["sleepy", "calm", "lullaby"] },
  { keyword: "想休息", tags: ["sleepy", "calm", "lullaby"] },
  { keyword: "昏昏欲睡", tags: ["sleepy", "calm", "lullaby"] },

  // 音樂風格
  { keyword: "搖滾", tags: ["rock", "alternative", "indie rock"] },
  { keyword: "金屬", tags: ["hard rock", "classic rock", "arena rock"] },
  { keyword: "重金屬", tags: ["heavy metal", "thrash metal", "death metal"] },
  { keyword: "龐克搖滾", tags: ["punk rock", "pop punk", "garage rock"] },
  { keyword: "另類搖滾", tags: ["alternative rock", "indie rock", "grunge"] },
  { keyword: "獨立搖滾", tags: ["indie rock", "lo-fi", "post-punk"] },
  {
    keyword: "民謠搖滾",
    tags: ["folk rock", "acoustic rock", "singer-songwriter"],
  },
  { keyword: "雷鬼", tags: ["reggae,", "chill", "jamaica"] },
  { keyword: "拉丁", tags: ["latin", "salsa", "reggaeton"] },
  { keyword: "靈魂樂", tags: ["soul", "r&b", "groove"] },
  { keyword: "靈魂", tags: ["soul", "r&b", "groove"] },
  { keyword: "福音", tags: ["gospel", "choir", "spiritual"] },
  { keyword: "爵士", tags: ["jazz", "smooth jazz", "bebop"] },
  { keyword: "藍調", tags: ["blues", "soul", "rhythm and blues"] },
  { keyword: "古典", tags: ["classical", "symphony", "piano"] },
  { keyword: "電子", tags: ["edm", "electronic", "techno"] },
  { keyword: "嘻哈", tags: ["hip hop", "rap", "trap"] },
  { keyword: "實驗", tags: ["experimental", "avant-garde", "ambient"] },
  { keyword: "龐克", tags: ["punk", "garage rock", "post-punk"] },
  { keyword: "流行", tags: ["pop", "top hits", "mainstream"] },
  { keyword: "民俗", tags: ["folk", "traditional", "cultural"] },
  { keyword: "民謠", tags: ["folk", "acoustic", "singer-songwriter"] },
  { keyword: "鄉村", tags: ["folk", "acoustic", "singer-songwriter"] },
  { keyword: "童謠", tags: ["children's music", "nursery rhymes", "kids"] },
  { keyword: "兒歌", tags: ["children's songs", "kids", "family"] },
  { keyword: "世界音樂", tags: ["world music", "global", "cultural fusion"] },
  { keyword: "動漫", tags: ["anime", "japanese", "otaku"] },
  { keyword: "獨立", tags: ["indie", "independent", "alternative"] },
  { keyword: "遊戲", tags: ["gaming", "video game", "soundtrack"] },
  { keyword: "環境", tags: ["ambient", "nature", "soundscape"] },
  { keyword: "電視劇", tags: ["tv drama", "series", "soap opera"] },
  { keyword: "紀錄片", tags: ["documentary", "narrative", "storytelling"] },
  { keyword: "電台", tags: ["radio", "broadcast", "live"] },
  { keyword: "podcast", tags: ["podcast", "talk show", "discussion"] },
  {
    keyword: "電影原聲",
    tags: ["movie soundtrack", "film score", "cinematic"],
  },

  // 語言
  { keyword: "KPOP", tags: ["k-pop", "korean", "girl group"] },
  { keyword: "台灣流行", tags: ["taiwan pop", "mandopop", "taiwanese"] },
  { keyword: "JPOP", tags: ["j-pop", "japanese", "anime"] },
  { keyword: "台語", tags: ["taiwanese", "hokkien", "trot"] },
  { keyword: "粵語", tags: ["cantonese", "cantopop", "hong kong"] },
  { keyword: "客語", tags: ["hakka", "taiwanese"] },
  { keyword: "原住民", tags: ["indigenous", "aboriginal", "folk"] },
  { keyword: "英語", tags: ["english", "international", "pop"] },
  { keyword: "英文", tags: ["english", "international", "pop"] },
  { keyword: "華語", tags: ["mandarin", "c-pop", "taiwan"] },
  { keyword: "中文", tags: ["mandarin", "c-pop", "taiwan"] },
  { keyword: "韓語", tags: ["korean", "k-pop"] },
  { keyword: "韓文", tags: ["korean", "k-pop"] },
  { keyword: "日語", tags: ["japanese", "j-pop", "anime"] },
  { keyword: "日文", tags: ["japanese", "j-pop", "anime"] },
  { keyword: "法語", tags: ["french", "chanson", "francophone"] },
  { keyword: "法文", tags: ["french", "chanson", "francophone"] },
  { keyword: "西班牙語", tags: ["spanish", "latin pop", "reggaeton"] },
  { keyword: "西班牙文", tags: ["spanish", "latin pop", "reggaeton"] },

  // 生活場景/用途
  { keyword: "運動", tags: ["sports", "workout", "energetic"] },
  { keyword: "讀書", tags: ["study", "focus", "office"] },
  { keyword: "工作", tags: ["work", "office", "concentration"] },
  { keyword: "開車", tags: ["driving", "road trip", "car music"] },
  { keyword: "聚會", tags: ["party", "gathering", "celebration"] },
  { keyword: "約會", tags: ["date", "romantic", "couple"] },
  { keyword: "睡前", tags: ["bedtime", "lullaby", "sleepy"] },
  { keyword: "背景音樂", tags: ["background music", "ambient", "chill"] },
  { keyword: "清晨", tags: ["morning", "fresh start", "upbeat"] },
  { keyword: "夜晚", tags: ["nighttime", "chill", "relaxing"] },
  { keyword: "旅行", tags: ["travel", "adventure", "exploration"] },
  { keyword: "慶祝", tags: ["celebration", "festive", "joyful"] },
  { keyword: "節日", tags: ["holiday", "festive", "seasonal"] },

  // 年代
  { keyword: "復古", tags: ["retro", "80s", "disco"] },
  { keyword: "懷舊", tags: ["nostalgic", "oldies", "classic"] },
  { keyword: "70年代", tags: ["retro", "70s", "classic"] },
  { keyword: "70", tags: ["retro", "70s", "classic"] },
  { keyword: "80年代", tags: ["disco", "80s", "synth"] },
  { keyword: "80", tags: ["disco", "80s", "synth"] },
  { keyword: "90年代", tags: ["90s", "grunge", "pop punk"] },
  { keyword: "90", tags: ["90s", "grunge", "pop punk"] },
  { keyword: "2000年代", tags: ["2000s", "pop rock", "hip hop"] },
  { keyword: "2000", tags: ["2000s", "pop rock", "hip hop"] },
  { keyword: "2010年代", tags: ["2010s", "indie pop", "trap"] },
  { keyword: "2010", tags: ["2010s", "indie pop", "trap"] },
  { keyword: "千禧年", tags: ["2000s", "y2k", "pop"] },
  { keyword: "現代", tags: ["modern", "current hits", "trending"] },

  // 其他
  { keyword: "輕快", tags: ["upbeat", "happy", "fast tempo"] },
  { keyword: "慢節奏", tags: ["slow", "ballad", "relaxing"] },
  { keyword: "舞曲", tags: ["dance", "club", "party"] },
  { keyword: "情歌", tags: ["love", "ballad", "romantic"] },
  { keyword: "老歌", tags: ["oldies", "classic hits", "vintage"] },
  { keyword: "潮流", tags: ["trending", "viral", "new release"] },
  { keyword: "電影", tags: ["soundtrack", "movie", "cinematic"] },
  { keyword: "隨便", tags: ["random", "anything", "variety"] },
  { keyword: "其他", tags: ["other", "miscellaneous", "various"] },
  { keyword: "藝術", tags: ["art music", "avant-garde", "experimental"] },
];
