// utils/emotionData.js
export default [
  { keyword: "開心", tags: ["happy", "energetic", "pop"] },
  { keyword: "難過", tags: ["sad", "slow", "piano"] },
  { keyword: "放鬆", tags: ["chill", "lofi", "acoustic"] },
  { keyword: "生氣", tags: ["angry", "rock", "metal"] },
  { keyword: "戀愛", tags: ["romantic", "love", "r&b"] },
  { keyword: "失戀", tags: ["heartbreak", "sad", "ballad"] },
  { keyword: "猶豫", tags: ["hesitant", "uncertain", "soft"] },
  { keyword: "憂鬱", tags: ["melancholy", "depressed", "emo"] },
  { keyword: "興奮", tags: ["excited", "dance", "upbeat"] },
  { keyword: "緊張", tags: ["tense", "intense", "dramatic"] },
  { keyword: "驚喜", tags: ["surprised", "unexpected", "quirky"] },
  { keyword: "疲憊", tags: ["tired", "calm", "ambient"] },
  { keyword: "焦慮", tags: ["anxious", "nervous", "chill"] },
  { keyword: "無聊", tags: ["bored", "chill", "easy-listening"] },
  { keyword: "平靜", tags: ["calm", "relaxing", "meditative"] },
  { keyword: "驚恐", tags: ["scared", "horror", "dark"] },
  { keyword: "期待", tags: ["excited", "anticipation", "upbeat"] },
  { keyword: "驚艷", tags: ["amazed", "wow", "inspiring"] },
  { keyword: "疑惑", tags: ["confused", "mysterious", "experimental"] },
  { keyword: "平淡", tags: ["neutral", "background", "easy-listening"] },
  { keyword: "搖滾", tags: ["rock", "alternative", "indie rock"] },
  { keyword: "金屬", tags: ["hard rock", "classic rock", "arena rock"] },
  { keyword: "爵士", tags: ["jazz", "smooth jazz", "bebop"] },
  { keyword: "藍調", tags: ["blues", "soul", "rhythm and blues"] },
  { keyword: "古典", tags: ["classical", "symphony", "piano"] },
  { keyword: "電子", tags: ["edm", "electronic", "techno"] },
  { keyword: "嘻哈", tags: ["hip hop", "rap", "trap"] },
  { keyword: "民謠", tags: ["folk", "acoustic", "singer-songwriter"] },
  { keyword: "實驗", tags: ["experimental", "avant-garde", "ambient"] },
  { keyword: "龐克", tags: ["punk", "garage rock", "post-punk"] },
  { keyword: "流行", tags: ["pop", "top hits", "mainstream"] },
  { keyword: "KPOP", tags: ["k-pop", "korean", "girl group"] },
  { keyword: "台灣流行", tags: ["taiwan pop", "mandopop", "taiwanese"] },
  { keyword: "JPOP", tags: ["j-pop", "japanese", "anime"] },
  { keyword: "台語", tags: ["taiwanese", "hokkien", "trot"] },
  { keyword: "英文", tags: ["english", "international", "pop"] },
  { keyword: "中文", tags: ["mandarin", "c-pop", "taiwan"] },
  { keyword: "韓文", tags: ["korean", "k-pop"] },
  { keyword: "日文", tags: ["japanese", "j-pop", "anime"] },
  { keyword: "法文", tags: ["french", "chanson", "francophone"] },
  { keyword: "西班牙文", tags: ["spanish", "latin pop", "reggaeton"] },
  { keyword: "復古", tags: ["retro", "80s", "disco"] },
  { keyword: "輕快", tags: ["upbeat", "happy", "fast tempo"] },
  { keyword: "慢節奏", tags: ["slow", "ballad", "relaxing"] },
  { keyword: "舞曲", tags: ["dance", "club", "party"] },
  { keyword: "情歌", tags: ["love", "ballad", "romantic"] },
  { keyword: "老歌", tags: ["oldies", "classic hits", "vintage"] },
  { keyword: "潮流", tags: ["trending", "viral", "new release"] },
  { keyword: "電影", tags: ["soundtrack", "movie", "cinematic"] },
  { keyword: "動漫", tags: ["anime", "japanese", "otaku"] },
  { keyword: "遊戲", tags: ["gaming", "video game", "soundtrack"] },
  { keyword: "療癒", tags: ["healing", "soothing", "calming"] },
  { keyword: "環境", tags: ["ambient", "nature", "soundscape"] },
  { keyword: "旅行", tags: ["travel", "world music", "cultural"] },
  { keyword: "運動", tags: ["sports", "workout", "energetic"] },
  { keyword: "想睡", tags: ["sleepy", "calm", "lullaby"] },
  { keyword: "童謠", tags: ["children's music", "nursery rhymes", "kids"] },
  { keyword: "兒歌", tags: ["children's songs", "kids", "family"] },
  { keyword: "紀錄片", tags: ["documentary", "narrative", "storytelling"] },
  { keyword: "獨立", tags: ["indie", "independent", "alternative"] },
  { keyword: "電台", tags: ["radio", "broadcast", "live"] },
  { keyword: "podcast", tags: ["podcast", "talk show", "discussion"] },
  { keyword: "電視劇", tags: ["tv drama", "series", "soap opera"] },
  { keyword: "隨便", tags: ["random", "anything", "variety"] },
  { keyword: "其他", tags: ["other", "miscellaneous", "various"] },
  { keyword: "民俗", tags: ["folk", "traditional", "cultural"] },
  { keyword: "世界音樂", tags: ["world music", "global", "cultural fusion"] },
  { keyword: "藝術", tags: ["art music", "avant-garde", "experimental"] },
  {
    keyword: "電影原聲",
    tags: ["movie soundtrack", "film score", "cinematic"],
  },
];
